# **C3a**

In [2]:
# Necesarias para manejo de índices
!pip install rtree -q
!pip install pygeos -q

!pip install geopandas -q

     |████████████████████████████████| 1.0 MB 14.9 MB/s
     |████████████████████████████████| 2.1 MB 13.3 MB/s
     |████████████████████████████████| 1.0 MB 13.3 MB/s
     |████████████████████████████████| 6.3 MB 71.8 MB/s
     |████████████████████████████████| 16.7 MB 63.1 MB/s

In [3]:
import geopandas as gpd

In [4]:
terremotos = gpd.read_file("terremotos.csv")

In [5]:
terremotos.head(10)

,Date,Time,Latitude,Longitude,Type,Depth,Magnitude,ID,geometry
0,1965-01-02,13:44:18,19.246,145.616,Earthquake,131.6,6.0,ISCGEM860706,None
1,1965-01-04,11:29:49,1.863,127.352,Earthquake,80.0,5.8,ISCGEM860737,None
2,1965-01-05,18:05:58,-20.579,-173.972,Earthquake,20.0,6.2,ISCGEM860762,None
3,1965-01-08,18:49:43,-59.076,-23.557,Earthquake,15.0,5.8,ISCGEM860856,None
4,1965-01-09,13:32:50,11.938,126.427,Earthquake,15.0,5.8,ISCGEM860890,None
5,1965-01-10,13:36:32,-13.405,166.629,Earthquake,35.0,6.7,ISCGEM860922,None
6,1965-01-12,13:32:25,27.357,87.867,Earthquake,20.0,5.9,ISCGEM861007,None
7,1965-01-15,23:17:42,-13.309,166.212,Earthquake,35.0,6.0,ISCGEM861111,None
8,1965-01-16,11:32:37,-56.452,-27.043,Earthquake,95.0,6.0,ISCGEMSUP861125,None
9,1965-01-17,10:43:17,-24.563,178.487,Earthquake,565.0,5.8,ISCGEM861148,None

In [6]:
gdf = gpd.GeoDataFrame(
    terremotos, geometry=gpd.points_from_xy(terremotos.Longitude, terremotos.Latitude))
terremotos = gdf
display(terremotos.head(10))

,Date,Time,Latitude,Longitude,Type,Depth,Magnitude,ID,geometry
0,1965-01-02,13:44:18,19.246,145.616,Earthquake,131.6,6.0,ISCGEM860706,POINT (145.61600 19.24600)
1,1965-01-04,11:29:49,1.863,127.352,Earthquake,80.0,5.8,ISCGEM860737,POINT (127.35200 1.86300)
2,1965-01-05,18:05:58,-20.579,-173.972,Earthquake,20.0,6.2,ISCGEM860762,POINT (-173.97200 -20.57900)
3,1965-01-08,18:49:43,-59.076,-23.557,Earthquake,15.0,5.8,ISCGEM860856,POINT (-23.55700 -59.07600)
4,1965-01-09,13:32:50,11.938,126.427,Earthquake,15.0,5.8,ISCGEM860890,POINT (126.42700 11.93800)
5,1965-01-10,13:36:32,-13.405,166.629,Earthquake,35.0,6.7,ISCGEM860922,POINT (166.62900 -13.40500)
6,1965-01-12,13:32:25,27.357,87.867,Earthquake,20.0,5.9,ISCGEM861007,POINT (87.86700 27.35700)
7,1965-01-15,23:17:42,-13.309,166.212,Earthquake,35.0,6.0,ISCGEM861111,POINT (166.21200 -13.30900)
8,1965-01-16,11:32:37,-56.452,-27.043,Earthquake,95.0,6.0,ISCGEMSUP861125,POINT (-27.04300 -56.45200)
9,1965-01-17,10:43:17,-24.563,178.487,Earthquake,565.0,5.8,ISCGEM861148,POINT (178.48700 -24.56300)